import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'I must start off by admitting that I can\'t be fully objective about this book, because I\'m actually mentioned in it (which is very, very cool, isn\'t it?). One of my blog posts is reprinted, my list of why you should read children\'s books as an adult. Donalyn was also gracious enough to acknowledge me for linking so regularly to her blog, The Book Whisperer. Thanks for which are completely unnecessary, of course. I link to her posts because nearly all of them are about topics that I want to share with my readers. And they are all well-written and heart-felt. Just like the book. So really, it\'s not so much that I want to review this book, as it is that I want to ask everyone, especially teachers, to please read it. But I\'ll do my best to give you a bit more detail. ' 
  'Donalyn Miller\'s The Book Whisperer is a manual for teachers on how to raise kids who enjoy books. Donalyn is a sixth grade language arts and social studies teacher who has had tremendous success in turning even initially resistant children into avid readers. She sets ambitious goals for reading in her classroom, and her methods have paid brilliant dividends. The Book Whisperer is the book that she wished she had to read herself, when she first started teaching, her attempt to share her methods with other teachers, so that they can help grow readers too.'
  'I believe that The Book Whisperer is a must-read title for reading teachers, especially for elementary and middle school-age kids. I also think that anyone who cares about raising readers, whether teacher or not, will enjoy The Book Whisperer.'
  'Donalyn begins the book by describing her own development as a reader, before moving on to her early learning experiences as a teacher. She defines the types of readers that she has observed, using positive, rather than negative terminology. Thus "struggling readers" become "developing readers", and "reluctant readers" become "dormant readers" or "underground readers". Then she explains her current methods, including ways of finding time to prioritize reading in the classroom, and ways of building classroom libraries. She discusses her requirement that each child read 40 books (broken into a series of genres) during the classroom year, both reasons for this and success rates, and her own responsibility as a reading role model. She also discusses her recommended changes to (or elimination of) other common classroom techniques, such as the month-long whole-class dissection of a novel. Some of what she recommends is common-sense, while other sections will be more controversial. But everything that Donalyn says is backed up by a) her actual classroom experience and b) the high test scores recorded by her students.' 
  'The Book Whisperer is extensively referenced and indexed, and contains examples of forms filled out and letters submitted by students. There\'s also an "Ultimate Library List" appendix, compiled by Donalyn\'s students, which is worth the price of the book all by itself. There are lovely quotes about the joy of reading at the start of every chapter, and fun asides, like a list of "Unusual Places to Read by Mrs. Miller\'s Class".'
  'But if you ask me, what makes this book truly special is Donalyn\'s genuine passion for creating readers -- it comes through on every page. I must have 50 post-it flags on my copy - quotable passage after quotable passage. Here are just a few of the many, many examples that I could have chosen:';
}
